version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq

  messaging:
    build:
      context: ..
      dockerfile: docker/Dockerfile.messaging
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
